name: Android CI

on:
  push:
    branches: [ "main", "test" ]
  pull_request:
    branches: [ "main", "test" ]

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  JAVA_VERSION: "17"

jobs:
  build-test:
    name: Build • Unit tests • Lint
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      # Pull repo code
      - name: Checkout
        uses: actions/checkout@v4

      # Validate Gradle wrapper (security check)
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      # Set up Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      # Cache Gradle dependencies
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # (Optional) Restore google-services.json from secret if using Firebase
      - name: Restore google-services.json
        if: ${{ secrets.GOOGLE_SERVICES_JSON_B64 != '' }}
        run: |
          mkdir -p app
          echo "${{ secrets.GOOGLE_SERVICES_JSON_B64 }}" | base64 -d > app/google-services.json

      # Build Debug APK
      - name: Build Debug
        run: ./gradlew assembleDebug --stacktrace

      # Run Unit Tests
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      # Run Android Lint
      - name: Android Lint
        run: ./gradlew lintDebug

      # Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: ignore

      # Upload test & lint reports
      - name: Upload Test & Lint Reports
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            **/build/reports/tests/**/*
            **/build/reports/lint-results*.*
